export default `Bob Pettit
Bob Cousy
Bill Russell
Bob Pettit
Wilt Chamberlain
Bill Russell
Bill Russell
Bill Russell
Oscar Robertson
Bill Russell
Wilt Chamberlain
Wilt Chamberlain
Wilt Chamberlain
Wes Unseld
Willis Reed
Kareem Abdul-Jabbar
Kareem Abdul-Jabbar
Dace Cowens
Kareem Abdul-Jabbar
Bob McAdoo
Kareem Abdul-Jabbar
Kareem Abdul-Jabbar
Bill Walton
Moses Malone
Kareem Abdul-Jabbar
Julius Erving
Moses Malone
Moses Malone
Larry Bird
Larry Bird
Larry Bird
Magic Johnson
Michael Jordan
Magic Johnson
Magic Johnson
Michael Jordan
Michael Jordan
Charles Barkley
Hakeem Olajuwon
David Robinson
Michael Jordan
Karl Malone
Michael Jordan
Karl Malone
Shaquille O’Neal
Allen Iverson
Tim Duncan
Tim Duncan
Kevin Garnett
Steve Nash
Steve Nash
Dirk Nowitzki
Kobe Bryant
LeBron James
LeBron James
Derrick Rose
LeBron James
LeBron James
Kevin Durant
Stephen Curry
Stephen Curry
Russell Westbrook
James Harden
Giannis Antetokounmpo`.split('\n');